<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Hospital.Tools.NeonPasswordSetup</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../backend/Hospital.Infrastructure/Hospital.Infrastructure.csproj" />
  </ItemGroup>
</Project>
