// <auto-generated />
using System;
using Hospital.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hospital.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Core.Audit.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorUserProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_profile_id");

                    b.Property<long?>("AffectedEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("affected_entity_id");

                    b.Property<string>("AffectedEntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("affected_entity_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("audit_event_pkey");

                    b.HasIndex("ActorUserProfileId", "OccurredAtUtc")
                        .HasDatabaseName("audit_event_actor_occurred_at_utc_idx");

                    b.HasIndex("AffectedEntityType", "AffectedEntityId", "OccurredAtUtc")
                        .HasDatabaseName("audit_event_affected_entity_occurred_at_utc_idx");

                    b.ToTable("audit_event", null, t =>
                        {
                            t.HasCheckConstraint("audit_event_action_check", "length(btrim(action)) > 0");

                            t.HasCheckConstraint("audit_event_affected_entity_type_check", "length(btrim(affected_entity_type)) > 0");

                            t.HasCheckConstraint("audit_event_metadata_size_check", "metadata_json IS NULL OR length(metadata_json::text) <= 4000");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Consultations.Consultation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("appointment_id");

                    b.Property<string>("CareInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("care_instructions");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("clinical_notes");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Outcome")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("outcome");

                    b.Property<string>("PatientSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("patient_summary");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("consultation_pkey");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("consultation_appointment_id_unique");

                    b.ToTable("consultation", null, t =>
                        {
                            t.HasCheckConstraint("consultation_completion_check", "(status = 'Draft' AND completed_at_utc IS NULL) OR (status = 'Completed' AND completed_at_utc IS NOT NULL AND completed_at_utc >= started_at_utc AND outcome IS NOT NULL AND length(btrim(outcome)) > 0 AND clinical_notes IS NOT NULL AND length(btrim(clinical_notes)) > 0 AND patient_summary IS NOT NULL AND length(btrim(patient_summary)) > 0 AND care_instructions IS NOT NULL AND length(btrim(care_instructions)) > 0)");

                            t.HasCheckConstraint("consultation_status_check", "status IN ('Draft', 'Completed')");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Medications.Medication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Classification")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("DoseForm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dose_form");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at_utc");

                    b.Property<string>("RxCui")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rx_cui");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Strength")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strength");

                    b.HasKey("Id")
                        .HasName("medication_pkey");

                    b.HasIndex("RxCui")
                        .IsUnique()
                        .HasDatabaseName("medication_rx_cui_unique");

                    b.ToTable("medication", null, t =>
                        {
                            t.HasCheckConstraint("medication_display_name_check", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("medication_rx_cui_check", "length(btrim(rx_cui)) > 0");

                            t.HasCheckConstraint("medication_source_check", "source IN ('RxNorm', 'SeededFallback')");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Pharmacy.Fulfillment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedPharmacistProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_pharmacist_profile_id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DispensedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispensed_at_utc");

                    b.Property<long>("PrescriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("prescription_id");

                    b.Property<DateTimeOffset?>("ReadyAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at_utc");

                    b.Property<DateTimeOffset?>("ReviewStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("fulfillment_pkey");

                    b.HasIndex("AssignedPharmacistProfileId")
                        .HasDatabaseName("fulfillment_assigned_pharmacist_profile_id_idx");

                    b.HasIndex("PrescriptionId")
                        .IsUnique()
                        .HasDatabaseName("fulfillment_prescription_id_unique");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("fulfillment_status_created_at_utc_idx");

                    b.ToTable("fulfillment", null, t =>
                        {
                            t.HasCheckConstraint("fulfillment_assignment_check", "(assigned_pharmacist_profile_id IS NULL) = (review_started_at_utc IS NULL)");

                            t.HasCheckConstraint("fulfillment_state_check", "(status = 'Pending' AND assigned_pharmacist_profile_id IS NULL AND review_started_at_utc IS NULL AND ready_at_utc IS NULL AND dispensed_at_utc IS NULL AND cancelled_at_utc IS NULL) OR (status = 'InReview' AND assigned_pharmacist_profile_id IS NOT NULL AND review_started_at_utc IS NOT NULL AND ready_at_utc IS NULL AND dispensed_at_utc IS NULL AND cancelled_at_utc IS NULL) OR (status = 'Ready' AND assigned_pharmacist_profile_id IS NOT NULL AND review_started_at_utc IS NOT NULL AND ready_at_utc IS NOT NULL AND dispensed_at_utc IS NULL AND cancelled_at_utc IS NULL) OR (status = 'Dispensed' AND assigned_pharmacist_profile_id IS NOT NULL AND review_started_at_utc IS NOT NULL AND ready_at_utc IS NOT NULL AND dispensed_at_utc IS NOT NULL AND cancelled_at_utc IS NULL) OR (status = 'Cancelled' AND cancelled_at_utc IS NOT NULL AND dispensed_at_utc IS NULL)");

                            t.HasCheckConstraint("fulfillment_status_check", "status IN ('Pending', 'InReview', 'Ready', 'Dispensed', 'Cancelled')");

                            t.HasCheckConstraint("fulfillment_timestamp_order_check", "(review_started_at_utc IS NULL OR review_started_at_utc >= created_at_utc) AND (ready_at_utc IS NULL OR (review_started_at_utc IS NOT NULL AND ready_at_utc >= review_started_at_utc)) AND (dispensed_at_utc IS NULL OR (ready_at_utc IS NOT NULL AND dispensed_at_utc >= ready_at_utc)) AND (cancelled_at_utc IS NULL OR cancelled_at_utc >= COALESCE(ready_at_utc, review_started_at_utc, created_at_utc))");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Prescriptions.Prescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint")
                        .HasColumnName("consultation_id");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dose");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("instructions");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("MedicationDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("medication_display_name_snapshot");

                    b.Property<long>("MedicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("medication_id");

                    b.Property<long>("PatientProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_profile_id");

                    b.Property<long>("PrescriberClinicianProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("prescriber_clinician_profile_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RxCuiSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rx_cui_snapshot");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("prescription_pkey");

                    b.HasIndex("ConsultationId")
                        .HasDatabaseName("prescription_consultation_id_idx");

                    b.HasIndex("MedicationId")
                        .HasDatabaseName("prescription_medication_id_idx");

                    b.HasIndex("PatientProfileId")
                        .HasDatabaseName("prescription_patient_profile_id_idx");

                    b.HasIndex("PrescriberClinicianProfileId")
                        .HasDatabaseName("prescription_prescriber_clinician_profile_id_idx");

                    b.ToTable("prescription", null, t =>
                        {
                            t.HasCheckConstraint("prescription_cancellation_check", "(status = 'Issued' AND cancelled_at_utc IS NULL) OR (status = 'Cancelled' AND cancelled_at_utc IS NOT NULL AND cancelled_at_utc >= issued_at_utc)");

                            t.HasCheckConstraint("prescription_dose_check", "length(btrim(dose)) > 0");

                            t.HasCheckConstraint("prescription_instructions_check", "length(btrim(instructions)) > 0");

                            t.HasCheckConstraint("prescription_medication_name_snapshot_check", "length(btrim(medication_display_name_snapshot)) > 0");

                            t.HasCheckConstraint("prescription_quantity_check", "quantity > 0");

                            t.HasCheckConstraint("prescription_rx_cui_snapshot_check", "length(btrim(rx_cui_snapshot)) > 0");

                            t.HasCheckConstraint("prescription_status_check", "status IN ('Issued', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Profiles.ClinicianProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<string>("StaffIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("staff_identifier");

                    b.Property<long>("UserProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id")
                        .HasName("clinician_profile_pkey");

                    b.HasIndex("StaffIdentifier")
                        .IsUnique()
                        .HasDatabaseName("clinician_profile_staff_identifier_unique");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasDatabaseName("clinician_profile_user_profile_id_unique");

                    b.ToTable("clinician_profile", null, t =>
                        {
                            t.HasCheckConstraint("clinician_profile_specialty_check", "length(btrim(specialty)) > 0");

                            t.HasCheckConstraint("clinician_profile_staff_identifier_check", "length(btrim(staff_identifier)) > 0");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Profiles.PatientProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AllergySummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("allergy_summary");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("medical_record_number");

                    b.Property<long>("UserProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id")
                        .HasName("patient_profile_pkey");

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique()
                        .HasDatabaseName("patient_profile_medical_record_number_unique");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasDatabaseName("patient_profile_user_profile_id_unique");

                    b.ToTable("patient_profile", null, t =>
                        {
                            t.HasCheckConstraint("patient_profile_medical_record_number_check", "length(btrim(medical_record_number)) > 0");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Profiles.PharmacistProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("PharmacyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pharmacy_name");

                    b.Property<string>("StaffIdentifier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("staff_identifier");

                    b.Property<long>("UserProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id")
                        .HasName("pharmacist_profile_pkey");

                    b.HasIndex("StaffIdentifier")
                        .IsUnique()
                        .HasDatabaseName("pharmacist_profile_staff_identifier_unique");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasDatabaseName("pharmacist_profile_user_profile_id_unique");

                    b.ToTable("pharmacist_profile", null, t =>
                        {
                            t.HasCheckConstraint("pharmacist_profile_pharmacy_name_check", "length(btrim(pharmacy_name)) > 0");

                            t.HasCheckConstraint("pharmacist_profile_staff_identifier_check", "length(btrim(staff_identifier)) > 0");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Profiles.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Auth0Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth0_subject");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("profile_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_status");

                    b.HasKey("Id")
                        .HasName("user_profile_pkey");

                    b.HasIndex("Auth0Subject")
                        .IsUnique()
                        .HasDatabaseName("user_profile_auth0_subject_unique");

                    b.ToTable("user_profile", null, t =>
                        {
                            t.HasCheckConstraint("user_profile_account_status_check", "account_status IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("user_profile_auth0_subject_check", "length(btrim(auth0_subject)) > 0");

                            t.HasCheckConstraint("user_profile_display_name_check", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("user_profile_profile_type_check", "profile_type IN ('Patient', 'Doctor', 'Pharmacist', 'Administrator')");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Scheduling.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("AvailabilitySlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("availability_slot_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("PatientProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_profile_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("appointment_pkey");

                    b.HasIndex("AvailabilitySlotId")
                        .IsUnique()
                        .HasDatabaseName("appointment_active_slot_unique")
                        .HasFilter("status <> 'Cancelled'");

                    b.HasIndex("AvailabilitySlotId", "Status")
                        .HasDatabaseName("appointment_availability_slot_status_idx");

                    b.HasIndex("PatientProfileId", "Status")
                        .HasDatabaseName("appointment_patient_profile_status_idx");

                    b.ToTable("appointment", null, t =>
                        {
                            t.HasCheckConstraint("appointment_cancellation_check", "(status = 'Cancelled' AND cancelled_at_utc IS NOT NULL AND cancelled_at_utc >= created_at_utc) OR (status <> 'Cancelled' AND cancelled_at_utc IS NULL AND cancellation_reason IS NULL)");

                            t.HasCheckConstraint("appointment_reason_check", "length(btrim(reason)) > 0");

                            t.HasCheckConstraint("appointment_status_check", "status IN ('Scheduled', 'InProgress', 'Completed', 'Cancelled', 'NoShow')");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Scheduling.AvailabilitySlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("ClinicianProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("clinician_profile_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("availability_slot_pkey");

                    b.HasIndex("ClinicianProfileId", "StartsAtUtc")
                        .IsUnique()
                        .HasDatabaseName("availability_slot_clinician_start_unique");

                    b.ToTable("availability_slot", null, t =>
                        {
                            t.HasCheckConstraint("availability_slot_time_range_check", "ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("Hospital.Core.Audit.AuditEvent", b =>
                {
                    b.HasOne("Hospital.Core.Profiles.UserProfile", "ActorUserProfile")
                        .WithMany()
                        .HasForeignKey("ActorUserProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("audit_event_actor_user_profile_id_fkey");

                    b.Navigation("ActorUserProfile");
                });

            modelBuilder.Entity("Hospital.Core.Consultations.Consultation", b =>
                {
                    b.HasOne("Hospital.Core.Scheduling.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("Hospital.Core.Consultations.Consultation", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("consultation_appointment_id_fkey");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Hospital.Core.Pharmacy.Fulfillment", b =>
                {
                    b.HasOne("Hospital.Core.Profiles.PharmacistProfile", "AssignedPharmacistProfile")
                        .WithMany()
                        .HasForeignKey("AssignedPharmacistProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fulfillment_assigned_pharmacist_profile_id_fkey");

                    b.HasOne("Hospital.Core.Prescriptions.Prescription", "Prescription")
                        .WithOne()
                        .HasForeignKey("Hospital.Core.Pharmacy.Fulfillment", "PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fulfillment_prescription_id_fkey");

                    b.Navigation("AssignedPharmacistProfile");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Hospital.Core.Prescriptions.Prescription", b =>
                {
                    b.HasOne("Hospital.Core.Consultations.Consultation", "Consultation")
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("prescription_consultation_id_fkey");

                    b.HasOne("Hospital.Core.Medications.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("prescription_medication_id_fkey");

                    b.HasOne("Hospital.Core.Profiles.PatientProfile", "PatientProfile")
                        .WithMany()
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("prescription_patient_profile_id_fkey");

                    b.HasOne("Hospital.Core.Profiles.ClinicianProfile", "PrescriberClinicianProfile")
                        .WithMany()
                        .HasForeignKey("PrescriberClinicianProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("prescription_prescriber_clinician_profile_id_fkey");

                    b.Navigation("Consultation");

                    b.Navigation("Medication");

                    b.Navigation("PatientProfile");

                    b.Navigation("PrescriberClinicianProfile");
                });

            modelBuilder.Entity("Hospital.Core.Profiles.ClinicianProfile", b =>
                {
                    b.HasOne("Hospital.Core.Profiles.UserProfile", "UserProfile")
                        .WithOne()
                        .HasForeignKey("Hospital.Core.Profiles.ClinicianProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("clinician_profile_user_profile_id_fkey");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Hospital.Core.Profiles.PatientProfile", b =>
                {
                    b.HasOne("Hospital.Core.Profiles.UserProfile", "UserProfile")
                        .WithOne()
                        .HasForeignKey("Hospital.Core.Profiles.PatientProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("patient_profile_user_profile_id_fkey");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Hospital.Core.Profiles.PharmacistProfile", b =>
                {
                    b.HasOne("Hospital.Core.Profiles.UserProfile", "UserProfile")
                        .WithOne()
                        .HasForeignKey("Hospital.Core.Profiles.PharmacistProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("pharmacist_profile_user_profile_id_fkey");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Hospital.Core.Scheduling.Appointment", b =>
                {
                    b.HasOne("Hospital.Core.Scheduling.AvailabilitySlot", "AvailabilitySlot")
                        .WithMany()
                        .HasForeignKey("AvailabilitySlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("appointment_availability_slot_id_fkey");

                    b.HasOne("Hospital.Core.Profiles.PatientProfile", "PatientProfile")
                        .WithMany()
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("appointment_patient_profile_id_fkey");

                    b.Navigation("AvailabilitySlot");

                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("Hospital.Core.Scheduling.AvailabilitySlot", b =>
                {
                    b.HasOne("Hospital.Core.Profiles.ClinicianProfile", "ClinicianProfile")
                        .WithMany()
                        .HasForeignKey("ClinicianProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("availability_slot_clinician_profile_id_fkey");

                    b.Navigation("ClinicianProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
